export const automationsContent = {
  hero: {
    eyebrow: "AI Automation & Implementation",
    title: "Automate the work that slows your business down.",
    text:
      "We analyse repetitive processes, identify where automation can create real value and build practical systems adapted to the way your organisation already works.",
    primary: { label: "Request a process assessment", href: "#contact" },
    secondary: { label: "See what can be automated", href: "#use-cases" },
    note:
      "No generic automation packages. Every workflow begins with the actual process.",
  },
  problems: [
    ["Information copied manually between tools", "Repeated handoffs create delay and avoidable errors."],
    ["Leads stored in different places", "Important context becomes fragmented across files and inboxes."],
    ["Repetitive email preparation", "Teams rewrite similar messages instead of focusing on the conversation."],
    ["Research repeated from the beginning", "Sources and findings are difficult to reuse consistently."],
    ["Documents difficult to organise", "Useful knowledge exists, but is hard to retrieve when needed."],
    ["Reports assembled manually", "Recurring updates take time to collect, format and check."],
    ["Disconnected content workflows", "Research, review and publication depend on manual coordination."],
    ["Follow-ups managed inconsistently", "Next actions are missed when ownership is unclear."],
    ["Low-value repetitive work", "Skilled people spend time maintaining processes instead of improving them."],
  ],
  useCases: [
    ["Lead generation and outreach", "Collect leads, organise contact information, prepare personalised outreach and track the status of each conversation."],
    ["Email and response workflows", "Prepare emails, organise follow-ups, detect replies and surface conversations that require human attention."],
    ["Research workflows", "Collect sources, structure information, organise findings and support repeatable research processes."],
    ["Content operations", "Move content from research to draft, review, publication and distribution through a structured workflow."],
    ["Documents and knowledge", "Organise files, extract useful information and create searchable internal knowledge systems."],
    ["Reporting", "Bring together information from different sources and reduce repetitive report preparation."],
    ["Internal tools", "Create lightweight dashboards, databases and interfaces adapted to the organisation’s needs."],
    ["Tool integration", "Connect existing tools through APIs and automation platforms to reduce manual handoffs."],
  ],
  process: [
    ["Process assessment", "We understand the current workflow, its purpose and the people involved."],
    ["Opportunity mapping", "We identify repetitive tasks, bottlenecks and areas where automation is appropriate."],
    ["Workflow design", "We define what should be automated, what should remain human and how information moves."],
    ["Implementation", "We build the workflow using suitable tools, APIs and custom code."],
    ["Testing", "We test edge cases, permissions, errors and handoffs before launch."],
    ["Documentation and adoption", "We explain how the system works and provide practical documentation for continued use."],
  ],
  principles: [
    "Human approval where judgement is required",
    "Clear ownership of data and accounts",
    "No unnecessary tool complexity",
    "Documentation of the workflow",
    "Privacy-aware implementation",
    "Error handling and fallback processes",
    "Systems adapted to existing teams",
    "No automatic communication without explicit approval where inappropriate",
  ],
  caseStudy: {
    title: "Automating local-business prospecting.",
    text:
      "An internal 3C Trix workflow was designed to support the discovery and organisation of potential small-business website clients.",
    steps: [
      "Search businesses by category and location",
      "Collect public business information",
      "Store leads in Google Sheets",
      "Identify public contact channels",
      "Prepare personalised outreach",
      "Track follow-ups",
      "Monitor responses",
      "Maintain a do-not-contact list",
    ],
    note:
      "Human review remains part of discovery, contact selection and every outreach decision.",
  },
  technologies: [
    "AI models",
    "Google Workspace",
    "APIs",
    "JavaScript",
    "Python",
    "Supabase",
    "n8n",
    "Make",
    "Zapier",
    "Custom internal interfaces",
  ],
  audiences: [
    "Small and medium-sized businesses",
    "Startups",
    "Research teams",
    "Media and content teams",
    "Event organisations",
    "Operations teams",
    "Founders",
    "Professional-services businesses",
  ],
  faq: [
    ["What types of processes can be automated?", "Repetitive, rules-based and information-heavy workflows are often strong candidates. We assess each process before recommending automation."],
    ["Does every automation use artificial intelligence?", "No. Some workflows are better solved with standard automation, APIs or structured databases. Artificial intelligence is used only when it adds clear value."],
    ["Will automation replace the human team?", "The objective is usually to reduce repetitive work and support better decisions. Human review remains essential where context, judgement or responsibility is required."],
    ["Can you work with our existing tools?", "Yes. We first assess the current stack and prioritise solutions that integrate with existing systems where practical."],
    ["Do you provide documentation?", "Yes. Projects can include workflow documentation, setup guidance and support during adoption."],
    ["Can you maintain the automation?", "Maintenance and ongoing support can be discussed according to the system and business requirements."],
  ],
} as const;
