export const researchContent = {
  hero: {
    eyebrow: "Research & Content",
    title: "Research that makes complex technology understandable.",
    text:
      "We analyse emerging technologies, markets and business models, then transform that research into clear articles, reports, SEO content and editorial work.",
    primary: { label: "Discuss a research project", href: "#contact" },
    secondary: { label: "Explore selected work", href: "#portfolio" },
  },
  themes: [
    "Artificial Intelligence",
    "Digital Assets",
    "Stablecoins",
    "Blockchain Infrastructure",
    "Payments",
    "Agentic Commerce",
    "Financial Technology",
    "Technology Regulation",
    "Tokenisation",
    "Emerging Business Models",
  ],
  services: [
    ["Research articles", "Clear, source-led analysis for specialist and general audiences."],
    ["Long-form reports", "Structured research covering markets, technology, regulation and business implications."],
    ["SEO content", "Search-optimised content that maintains credibility, clarity and analytical depth."],
    ["Event coverage", "Articles, interviews and editorial coverage designed around conferences and industry events."],
    ["Executive briefings", "Concise research designed to support internal understanding and decision-making."],
    ["Website and product copy", "Clear technology communication for websites, product pages and company materials."],
    ["Editorial strategy", "Support in defining topics, formats, publishing priorities and content positioning."],
    ["Research-led social content", "Shorter content derived from substantive research rather than generic commentary."],
  ],
  experience: [
    ["The Big Whale", "Research and editorial work focused on digital assets, regulation, markets and financial technology."],
    ["European Blockchain Convention Barcelona", "Editorial and event-related content covering blockchain, digital assets and industry developments."],
    ["Digital Assets Forum London", "Content supporting discussion around institutional digital assets and financial infrastructure."],
    ["Stablecoin Insider", "Articles and report-related work focused on stablecoins, payments and blockchain-based financial infrastructure."],
    ["The Block", "Research experience within the digital-assets industry."],
  ],
  process: [
    ["Define the question", "Clarify the audience, objective, scope and level of technical depth."],
    ["Research", "Identify primary sources, data, industry context and competing interpretations."],
    ["Structure", "Organise the evidence into a clear argument and accessible narrative."],
    ["Write", "Produce accurate and readable content adapted to the publication or company voice."],
    ["Review", "Check sources, claims, terminology, structure and editorial requirements."],
    ["Publish or deliver", "Provide the final work in the required format, with links and supporting material."],
  ],
  principles: [
    "Sources close to factual claims",
    "Clear separation between evidence and interpretation",
    "Accessible explanations of technical subjects",
    "No unnecessary jargon",
    "No unsupported claims",
    "Writing adapted to the intended audience",
    "Research that connects technology to business and policy implications",
  ],
  faq: [
    ["What topics do you cover?", "Core areas include artificial intelligence, digital assets, stablecoins, blockchain, payments, agentic commerce, regulation and emerging financial infrastructure."],
    ["Do you write for technical and general audiences?", "Yes. The structure, terminology and level of explanation are adapted to the intended reader."],
    ["Can you follow an existing editorial voice?", "Yes. Research and writing can be adapted to existing tone, formatting and publication requirements."],
    ["Do you provide sources?", "Yes. Sources can be included according to the required format, with priority given to credible primary and authoritative sources."],
    ["Do you offer SEO content?", "Yes. Search optimisation can be integrated without reducing the analytical quality or readability of the content."],
    ["Can you cover events?", "Yes. Services may include event previews, interviews, session summaries, daily coverage and post-event analysis."],
  ],
} as const;
